import { Sliderdata  } from '../classes';

export const SLIDERDATA: Sliderdata[] = [
  { 
    id: 1, 
    title: 'Early European Settlers - 1669 -1770’s',
    detail: 'Many European explorers traveled to North America searching for riches and glory. Hernando De Soto most likely saw the confluence of the Ohio and Mississippi Rivers, but it was Rene Robert Cavelier, Sieur de La Salle that traveled the full length of the Ohio. La Salle’s interest in North America lay in the fur trade, and he frequently interacted with Native American tribes to learn about the land. By the 1770’s European settlers were present in Owensboro. Connection and communication between settlers began increasing in the 1775 in the form of stations and forts. Yellow Banks lay in Jefferson County until 1785 when Nelson County was created. In 1793 Nelson County was split and Yellow Banks became part of Hardin County, then Ohio County in 1799. Finally, in 1815, Daviess County was formed.',
    link: '/explore',
    image: '../assets/images/transportation/How_did_people_travel.png'
  },
    { 
    id: 2, 
    title: 'Hannah Severns - 1750-1780',
    detail: 'In the mid-1750’s Shawneecaptured Hannah Severns and her family in Point Pleasant, Virginia (now West Virginia). Hannah’s father was killed during the capture, and her mother’s tongue was cut out. The family was held captive for roughly nine years. In 1764, Colonel Henry Bouquet negotiated the release of Hannah and her family, along with many more white settlers. Hannah moved to Yellow Banks and claimed acreage near the Ohio River. Being an unmarried woman had its advantages:she had agency over her own affairs, and could legally own land in her own name. But Hannah did not stay in Yellow Banks for long. In the late summer of 1777, mounting tensions with Native American tribes forced Hannah and several other settlers to flee to Fort Harrod. There she met Lieutenant Benjamin Linn. Despite the dire situation and blockade, the two married on July 9th, 1777.When researching people in history, keep in mind there might be multiple spellings of their first or last names. Hannah’s last name is often spelled Soverns, Severins, Soverign, orSovereign. Use context clues like dates, locations, and other names to help you decipher the text.',
    link: '/explore',
    image: '../assets/images/culture/Hannah-Severns.png'
  },
    { 
    id: 3, 
    title: 'Settlers in Owensboro - 1797-1800’s',
    detail: 'William Smothers received land via the same land grant as Hannah Severns. He moved to Yellow Banks with his wife and sister and opened a trading post on the Ohio River. Unfortunately, the trading post was not necessarily a safe place; a keelboatman named Andrew Norris assaulted Smothers’ sister, and Smothers killed Norris. April 10, 1809, William Smothers stood trial for the murder, and the jury declared him not guilty; Smothers was represented by Joseph Hamilton Daviess. Joseph Hamilton Daveiss, a lawyer who unsuccessfully prosecuted Aaron Burr, moved to Yellow Banks in 1805 with his wife after receiving a land grant. He is the namesake of Daviess county, but due to a clerical error, “Daveiss” became “Daviess.” Yellow Banks became Rossborough in December 1816 after local land owner David Ross, but quickly changed to Owensboro in January 1817 in honor of Colonel Abraham Owen, who died at the battle of Tippecanoe.',
    link: '/explore',
    image: '../assets/images/culture/Settlers-in-Owensboro.png'
  },
    { 
    id: 4, 
    title: 'Slavery in Owensboro - 1700-1865',
    detail: 'One out of every five early Kentucky settlers was African American and most of them were enslaved. They were the blacksmiths, brick masons, carpenters, boat wrights and field hands that helped build Kentucky’s first stations, towns and farms. The Commonwealth legally viewed enslaved people as a form of property. These individuals were often used as collateral in business transactions, to pay off outstanding debts or to secure loans to purchase additional land or even other enslaved people. Estates included the estimated value of each enslaved person and taxes were levied on slave transactions. This became a valued source of revenue for both state and local governments. In Daviess County, like many parts of Kentucky, the corn crops and the particularly labor-intensive tobacco crops depended on an enslaved workforce. The raising of tobacco required nearly year-round attention and many local enslaved people also worked on and around the Ohio and Green Rivers, moving crops and cargo to markets near and far. The invention of the cotton gin resulted in an increased demand for labor in the south, and Kentucky became a major supplier of enslaved people to southern plantations and become known as a “slave grower” state. The General Assembly passed a law in 1833 prohibiting the importation of enslaved people into the Commonwealth, but the law was often ignored and was poorly enforced. “Hiring Out” enslaved people was a common practice in Kentucky’s agrarian society and allowed slave holders a continued monetary stream outside of growing seasons. Enslaved workers often received a portion of the “rental” fee as well and were allowed to keep this earned wage. Prior to statehood in 1792 and in the seventy-three years after, Kentuckians argued about the pros and cons of slavery. Only upon the ratification of the 13th Amendment on December 6, 1865 was slavery finally abolished in Kentucky.',
    link: '/explore',
    image: '../assets/images/culture/Slavery-in-Owensboro.png'
  },
    { 
    id: 5, 
    title: 'Josiah Henson - 1789-1883',
    detail: 'Josiah Henson, an enslaved African American, impacted the African American story in Owensboro and beyond. Isaac Riley sold Josiah to his brother Amos Riley, who owned a plantation in Daviess County. Josiah held a travel pass which allowed him unhindered travel via land or water between the plantation and Yellow Banks. Henson attempted to buy his freedom, but instead of honoring this Isaac Riley made plans to sell Josiah south. To protect his family and gain freedom, the Hensons fled north into Canada in 1830. Josiah established an Afro-Canadian community in Desden, Ontario, and made numerous trips back into slave states to free over 200 enslaved African Americans via the Underground Railroad. Enslaved African Americans sustained visions of freedom in their very survival and daily actions. They found ways to create their own identities in their work, families, church services and extended community. Some enslaved people saved hard-earned money from their “hired-out” jobs, and a relative few were able to purchase their way out of slavery. Freedom for others was the result of fleeing into the unknown, in hopes of gaining control of their own destinies. The majority of enslaved African Americans could not escape: only a small percentage were connected with someone, usually another African American, who could “lead” them to freedom. For the most part, these self-emancipating enslaved people were on their own, with no assistance, until crossing the Mississippi or Ohio River. Even then, there was no guarantee that a safe haven or helping hand would be found. The phrase “Underground Railroad” entered common usage in the mid-1840’s, and the movement is suggested to be the first real interracial coalition, even though it was run predominately by free African Americans living in the North.',
    link: '/explore',
    image: '../assets/images/culture/Josiah-Henson.png'
  },
    { 
    id: 6, 
    title: 'Judith & Charles Jackso - 1831-1890’s',
    detail: 'In 1831 Peter and Dolly Wilson gave birth to Judith (Judy) Wilson in Hawesville, Kentucky. Peter and Dolly were both born into slavery in Virginia; currently we don’t have information telling us how they came to Kentucky or where they were enslaved. Judy married Charles (Charlie) Jackson while they were enslaved by Christopher Jackson, on the Jackson farm in Masonville, Kentucky. Charles was a field hand and Judith worked in the Jackson house. Christopher Jackson often “hired out” Charles to neighbors in the Masonville area and allowed Charles to grow his own tobacco crop. Charles saved most of the money earned from these jobs. He stowed it in a tin can, hidden from everyone – including Judy. Judy and Charlie’s first child, Tazewell, was born in 1859, followed by Finley in 1861 and Melinda in 1863. Judy gave birth to their last child, Charles, in 1865. Charles Jackson and Stephen Simmons, a man enslaved near the Jacksonville farm, walked about 15 miles into Owensboro in November 1864 to enlist in the Union Army’s 6th U.S. Colored Calvary. They were officially out of reach of the slave owners. While the war ended in May 9, 1865, the soldiers were held in the army until 1866. Five days before the soldiers received their release to go home, Charles died from pneumonia. We don’t know if Charles and Judy knew she was pregnant before he left for the army. Stephen Simmons survived the war and traveled back to Kentucky where he found Judy and told her about Charlie’s “money tree” that hid his tin can containing $500. Stephen passed on a message from Charlie: “Keep shoes on the children’s feet until they were old enough to buy their own.” Judy continued to work for the Jacksons for several years after the war, until she found a farm to purchase. Eventually, she purchased a larger farm, supporting her family, the children’s school, and their church. One of the attached receipts mentions that she purchased a suit for the church pastor.',
    link: '/explore',
    image: '../assets/images/culture/Judy-and-Charles-Jackson.png'
  }

];